# STINTSY Major Course Output

### Group 3
### Members:

* Rohann Gabriel D. Dizon
* Rainier A. Dulatre

### Dataset Description

* The dataset comprises competitive gameplay statistics sourced from **Tetrio**, a modern, fast-paced multiplayer Tetris clone. It specifically tracks the performance and match data of the top 500 players in the Tetra League. The data is scraped from 61,935 match replays of the top 500 Tetra League players between January 22, 2024, and January 30, 2024.

* Source: Kaggle (https://www.kaggle.com/datasets/n3koasakura/tetr-io-top-players-replays/data)

### Structure of the Data
* ##### **Unit of Analysis**: Each individual row represents a single subframe piece placement (one block dropped) 
* ##### **Number of Observations/Rows**: 7,716,524 piece placements.
* ##### **Format**: Tabular data with 21 variables/columns.

* ### Description of Variables

| **Features/Variables** | **Description** |
|------------------------|-----------------|
| game_id | The unique ID for this game/replay (players in the same match get different IDs). |
| subframe | The subframe of this placement. There 60 frames per second and 10 subframes per frame, or 600 subframes per second, starting with subframe 0. |
| won | 1 if this placement is part of a replay that won its match. Otherwise, 0. |
| playfield | The 10x40 playfield right before the placement occured. The cells of the playfield are ordered left to right, bottom to top. The playfield is truncated once all the remaining cells are empty. An empty string is not a missing value, but instead represents a playfield where all cells are empty. Each cell is represented with the letter of its corresponding tetrimino, except for empty and garbage cells, which are represented with "N" and "G" respectively. |
| x | The x-coordinate of the center of the placed piece according to the "true rotations" used in the Super Rotation System. 0 indicates the leftmost column, 9 indicates the rightmost column. |
| y | The y-coordinate of the center of the placed piece according to the "true rotations" used in the Super Rotation System. 0 indicates the bottommost row, 39 indicates the topmost row. |
| r | The rotation of the placed piece according to the Super Rotation System. N(0) - North; E(R) - East; S(2) - South; W(L) - West  |
| placed | The type of piece placed. |
| hold | The type of piece currently being held. "N" means no piece is being held. |
| next | The types of the next 14 peices in the queue (only the first 5 are visible to the player). |
| cleared | The number of rows cleared with this placement. |
| garbage_cleared | The number of rows containing garbage cleared with this placement. |
| attack | The rows of garbage sent with this placement, before garbage blocking. |
| t_spin | The type of T-spin performed. N - None; M - Mini; F - Full |
| btb | The length of the back-to-back chain right before this placement. |
| combo | The length of the combo chain right before this placement. |
| immediate_garbage | The rows of incoming garbage in queue ready to be received (the actual amount that will be received is capped at 8). |
| incoming_garbage | The total rows of incoming garbage in queue. |
| rating | The player's Tetra League rating (25000 is the maximum rating). |
| glicko | The player's Tetra League Glicko-2 rating. |
| glicko_rd | The player's Tetra League Glicko-2 rating deviation. |

### Variables Used in this Study

This study used **14** of the 21 variables, which are `game_id`, `subframe`, `won`, `cleared`, `garbage_cleared`, `attack`, `t_spin`, `btb`, `combo`, `immediate_garbage`, `incoming_garbage`, `rating`, `glicko`, and `glicko_rd`.The reason for choosing these variables is its relevance to the group's desired prediction task for the models to be tackled later in the notebook. However, note that **these are not the final variables used in model training/validation/testing** as it proceeds through data cleaning and feature engineering.

### Importing Libraries

The following libraries are used throughout the project and are necessary to perform data preprocessing, analysis, visualizations, and model training, validation, and testing:

In [40]:
# Standard Library & System
import sys
import os
import itertools

# Data Manipulation & Visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr

# Scikit-learn
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, 
    classification_report, 
    confusion_matrix, 
    ConfusionMatrixDisplay
)

# Pytorch
import torch
import torch.optim as optim
import torch.nn as nn

# Custom Local Modules
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from src.neural_network import NeuralNetwork
from src.data_loader import DataLoader

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Raw Contents of the Dataset

In [41]:
df = pd.read_csv("../data/data.csv")

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7716524 entries, 0 to 7716523
Data columns (total 21 columns):
 #   Column             Dtype
---  ------             -----
 0   game_id            int64
 1   subframe           int64
 2   won                int64
 3   playfield          str
 4   x                  int64
 5   y                  int64
 6   r                  str
 7   placed             str
 8   hold               str
 9   next               str
 10  cleared            int64
 11  garbage_cleared    int64
 12  attack             int64
 13  t_spin             str
 14  btb                int64
 15  combo              int64
 16  immediate_garbage  int64
 17  incoming_garbage   int64
 18  rating             float64
 19  glicko             float64
 20  glicko_rd          float64
dtypes: float64(3), int64(12), str(6)
memory usage: 1.2 GB

In [43]:
df.shape

(7716524, 21)

In [44]:
df.head()

,game_id,subframe,won,playfield,x,y,r,placed,hold,next,...,garbage_cleared,attack,t_spin,btb,combo,immediate_garbage,incoming_garbage,rating,glicko,glicko_rd
0,1,67,1,NaN,4,0,N,I,N,JZSOTLSLIOJZTJ,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
1,1,170,1,NNNIIII,4,1,N,Z,J,SOTLSLIOJZTJTZ,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
2,1,339,1,NNNIIIINNNNNNNZZNNNNNNNZZ,6,1,E,S,J,OTLSLIOJZTJTZS,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
3,1,472,1,NNNIIIISNNNNNNZZSSNNNNNZZNS,8,0,N,O,J,TLSLIOJZTJTZSO,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624
4,1,602,1,NNNIIIISOONNNNZZSSOONNNZZNS,0,1,E,J,T,LSLIOJZTJTZSOI,...,0,0,N,0,0,0,0,24748.521484,2701.887695,62.212624

The code results above gives us insight about what the data looks like before being preprocessed. This also lets us verify that we are indeed dealing with 7,716,524 rows and 21 columns.

## Data Preprocessing

Prior to data exploration and analysis, data cleaning and preprocessing will be carried out to resolve any discrepancies in the dataset and avoid inaccurate results.

The following was checked and applied with the necessary cleaning procedures:

* Removing Unnecessary Variables
* Multiple Representations
* Missing Data
* Negative Values
* Incorrect Datatypes
* Default Values and Inconsistent Formatting
* Duplicate Data
* Data Inconsistencies
* Outliers
* Feature Engineering

### Removing Unnecessary Variables

As previously mentioned, this study only focused on *14* specific variables that are related to the prediction task, so other columns that are not needed are disregarded, specifically variables related to the spatial playfield.

In [45]:
unneeded_cols = ["playfield", "x", "y", "r", "next", "hold", "placed"]
present_unneeded = [col for col in unneeded_cols if col in df.columns]
df = df.drop(columns=present_unneeded)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7716524 entries, 0 to 7716523
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   game_id            int64
 1   subframe           int64
 2   won                int64
 3   cleared            int64
 4   garbage_cleared    int64
 5   attack             int64
 6   t_spin             str
 7   btb                int64
 8   combo              int64
 9   immediate_garbage  int64
 10  incoming_garbage   int64
 11  rating             float64
 12  glicko             float64
 13  glicko_rd          float64
dtypes: float64(3), int64(10), str(1)
memory usage: 824.2 MB

### Checking For Multiple Representations

This is done to check for multiple represenations in the categorical variables that will be used

In [46]:
df["won"].value_counts()

won
1    4274700
0    3441824
Name: count, dtype: int64

In [47]:
df["t_spin"].value_counts()

t_spin
N    7150022
F     527604
M      38898
Name: count, dtype: int64

The number of unique labels and values within `won` and `t_spin` are correctly represented and conform with the unique labels defined by the dataset's dictionary

### Checking For Missing Data

This is done to identify missing data or null values in each variable

In [48]:
df.isnull().any()

game_id              False
subframe             False
won                  False
cleared              False
garbage_cleared      False
attack               False
t_spin               False
btb                  False
combo                False
immediate_garbage    False
incoming_garbage     False
rating               False
glicko               False
glicko_rd            False
dtype: bool

No further processing is required regarding missing data as there are no presence of null values in any of the variables

### Checking for Negative Values

This is done to check for negative values, especially for the variables with a continuous numerical value. Given the context of the dataset and variables, there should ideally be no negative values.

In [49]:
numeric_cols = df.select_dtypes(include=["number"])
negative_counts = (numeric_cols < 0).sum()
print(negative_counts)

game_id              0
subframe             0
won                  0
cleared              0
garbage_cleared      0
attack               0
btb                  0
combo                0
immediate_garbage    0
incoming_garbage     0
rating               0
glicko               0
glicko_rd            0
dtype: int64

Results show that no negative values were found within the variables

### Checking for Incorrect Datatypes

This is done to check if the variables are currently assigned appropriate variables

In [50]:
df.dtypes

game_id                int64
subframe               int64
won                    int64
cleared                int64
garbage_cleared        int64
attack                 int64
t_spin                   str
btb                    int64
combo                  int64
immediate_garbage      int64
incoming_garbage       int64
rating               float64
glicko               float64
glicko_rd            float64
dtype: object

It shows that all variables are already assigned the appropriate variables

However, the current variables with numerical datatypes (int and float) could use a smaller-range for memory optimization purposes, especially useful during model training

In [51]:
int_cols = [
    "won",
    "game_id",
    "subframe",
    "cleared",
    "garbage_cleared",
    "attack",
    "btb",
    "combo",
    "immediate_garbage",
    "incoming_garbage",
]
float_cols = ["rating", "glicko", "glicko_rd"]
for col in int_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], downcast="integer", errors="coerce")
for col in float_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], downcast="float", errors="coerce")

df.dtypes

game_id                int32
subframe               int32
won                     int8
cleared                 int8
garbage_cleared         int8
attack                  int8
t_spin                   str
btb                     int8
combo                   int8
immediate_garbage       int8
incoming_garbage        int8
rating               float32
glicko               float32
glicko_rd            float32
dtype: object

### Checking for Default Values and Inconsistent Formatting

This is done to check for distinct values in every variable and identify whether it contains default values or inconsistent formatting among the values

In [52]:
for col in df:
    print(f"{col}: {df[col].unique()}")
    print("")

game_id: [     1      2      3 ... 124030 124031 124032]

subframe: [    67    170    339 ... 102556 103224 103661]

won: [1 0]

cleared: [0 2 1 4 3]

garbage_cleared: [0]

attack: [ 0  4  1  5  3  6  2  7  8 10  9 11 12 14 15 16 17 13 19 18 22 20]

t_spin: <StringArray>
['N', 'F', 'M']
Length: 3, dtype: str

btb: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54]

combo: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

immediate_garbage: [ 0  7  8  4  2  1  6 10 13  5  3  9 11 15 12 14 20 16 19 23 22 18 28 17
 21 26 25 24 31 27 32 36 30 40 35 41 33 29 34 38 37 69 78 49 42 50 43 51
 39 46 59 58 77 61 52 56]

incoming_garbage: [ 0  7 15  9  2  1  4  6  5  3 13 10 11  8 16 12 14 18 20 19 23 29 17 28
 22 24 21 26 25 27 31 32 34 36 30 40 35 41 33 38 37 69 78 49 42 50 43 51
 39 46 66 58 77 74 52 56 59 44]

rating: [24748.521 24820.71  24788.744 24830.146 24859.947 24887.217 24864.002
 24961.023 24713.244 24827.414 24737.203 24999.521 24991.893 24730.414
 24886.387 24929.59  24832.297 24709.613 24917.914 24825.25  24808.395
 24910.676 24713.307 24904.139 24964.734 24952.473 24952.492 24967.291
 24872.346 24876.947 24857.99  24924.229 24834.791 24930.447 24967.193
 24974.691 24984.186 24767.938 24914.426 24916.207 24886.336 24825.12
 24805.045 24750.25  24755.1   24797.262 24828.457 24894.14  24937.195
 24894.424 24917.064 24726.191 24766.162 24778.492 24724.658 24867.152
 24915.484 24967.264 24987.777 24909.371 24933.684 24968.213 24968.549
 24882.125 24847.633 24970.166 24855.367 24820.375 24704.047 24936.004
 24705.215 24875.89  24995.035 24946.271 24804.076 24763.998 24846.756
 24777.96  24921.703 24907.275 24906.328 24829.34  24704.904 24967.693
 24993.188 24966.71  24918.986 24984.781 24832.326 24966.24  24952.324
 24986.443 24774.994 24804.715 24917.523 24903.615 24922.383 24850.232
 24886.254 24966.744 24866.598 24960.055 24722.18  24766.717 24902.822
 24974.934 24819.602 24941.434 24992.703 24993.371 24963.105 24834.363
 24741.568 24958.176 24992.85  24948.861 24826.209 24798.695 24986.934
 24854.154 24713.01  24766.164 24978.76  24889.355 24933.693 24887.785
 24901.    24892.734 24806.299 24870.914 24984.25  24884.785 24842.482
 24886.258 24739.926 24769.527 24998.672 24997.002 24998.934 24798.246
 24736.4   24895.004 24954.293 24854.812 24991.69  24958.797 24900.883
 24763.463 24973.408 24953.334 24964.166 24987.09  24993.91  24989.594
 24705.621 24766.662 24767.867 24734.807 24720.92  24908.549 24983.658
 24730.06  24728.652 24719.248 24780.746 24913.307 24910.861 24880.113
 24963.174 24790.303 24771.697 24699.232 24712.287 24939.514 24771.611
 24953.6   24712.217 24796.934 24967.186 24976.82  24801.236 24785.734
 24802.025 24758.447 24755.803 24924.51  24753.514 24866.146 24898.13
 24978.762 24726.506 24705.684 24783.465 24736.99  24874.744 24743.047
 24908.623 24905.264 24891.926 24708.293 24931.32  24715.379 24958.457
 24780.596 24840.69  24814.932 24964.861 24776.514 24936.506 24710.98
 24954.555 24885.748 24816.092 24953.426 24965.059 24948.424 24884.227
 24978.086 24724.738 24927.803 24965.65  24932.299 24987.389 24982.566
 24984.383 24798.13  24732.086 24836.441 24871.701 24882.682 24873.549
 24802.39  24998.861 24998.973 24930.523 24827.61  24786.443 24757.734
 24922.74  24918.766 24913.348 24757.066 24919.627 24923.773 24925.146
 24711.025 24930.203 24958.912 24728.035 24978.924 24708.14  24753.25
 24868.56  24951.586 24710.393 24975.098 24832.389 24913.236 24915.178
 24980.46  24995.244 24780.732 24700.46  24930.953 24773.16  24740.016
 24711.768 24802.379 24749.613 24948.818 24770.158 24798.982 24849.018
 24988.42  24764.482 24987.23  24858.041 24833.463 24986.658 24941.64
 24997.129 24995.213 24767.82  24888.348 24890.314 24826.514 24759.117
 24904.764 24907.875 24999.227 24958.998 24801.986 24829.8   24971.404
 24743.982 24821.469 24845.713 24971.576 24938.11  24904.594 24974.47
 24805.105 24740.143 24981.703 24829.848 24868.434 24714.209 24745.896
 24979.986 24879.502 24726.582 24854.111 24718.81  24950.133 24742.105
 24775.988 24758.033 24911.164 24736.78  24846.924 24927.68  24940.97
 24817.904 24914.207 24860.793 24996.799 24881.521 24848.158 24925.105
 24750.025 24941.32  24892.97  24714.676 24711.707 24855.111 24855.295
 24754.223 24980.107 24908.781 24854.383 24839.402 24910.906 24774.088
 24707.426 24739.29  24703.367 24844.086 24893.055 24899.96  24702.863
 24744.37  24904.504 24849.514 24940.676 24861.547 24790.945 24951.275
 24980.47  24864.13  24954.95  24716.338 24718.025 24834.281 24985.393
 24950.389 24805.18  24854.059 24833.521 24792.197 24875.227 24698.324
 24984.56  24777.525 24880.129 24964.184 24988.36  24989.225 24777.223
 24732.357 24859.438 24705.186 24724.533 24983.178 24930.867 24927.775
 24705.674 24945.846 24979.555 24875.463 24818.549 24986.867 24746.521
 24957.203 24925.123 24972.207 24874.13  24989.396 24945.803 24832.98
 24843.674 24982.594 24964.943 24854.553 24905.867 24967.436 24863.055
 24949.164 24910.973 24708.037 24747.537 24993.936 24942.762 24701.662
 24857.77  24719.104 24974.305 24734.418 24954.666 24768.375 24995.01
 24794.85  24717.086 24844.486 24983.482 24901.816 24870.396 24939.994
 24729.768 24712.547 24755.9   24863.47  24743.764 24707.28  24808.795
 24958.871 24996.576 24736.482 24740.041 24748.254 24859.752 24978.441
 24708.354 24724.67  24781.562 24959.709 24916.771 24765.004 24772.582
 24738.13  24734.873 24798.477 24742.293 24742.717 24982.875 24921.295
 24907.652 24991.518 24990.72  24704.424 24775.71  24806.055 24771.936
 24704.58  24699.66  24729.992 24813.967 24700.943 24716.842 24826.922
 24781.725 24866.281 24699.094 24792.17  24725.738 24760.605 24841.367
 24923.414 24971.826 24707.05  24698.078 24872.742 24738.564 24777.043
 24707.309 24762.967 24956.559 24953.969]

glicko: [2701.8877 2791.867  2748.1938 2810.6868 2856.2388 2921.948  2867.176
 3193.4368 2668.7383 2811.6335 2694.0974 4373.42   3606.3906 2683.1963
 2917.226  3043.3848 2809.0107 2677.7761 2998.0535 2806.0457 2780.3904
 2976.2146 2666.3682 2965.2788 3219.058  3161.7605 3148.018  3241.7844
 2883.4224 2894.9565 2852.4678 3018.0234 2813.259  3041.1487 3238.321
 3327.2412 3430.538  2723.6504 2986.7607 2998.9922 2912.1992 2797.8997
 2768.9521 2703.5435 2710.0752 2758.6821 2808.789  2930.2354 3067.2615
 2934.391  2994.586  2688.2932 2721.5579 2735.4072 2678.084  2870.942
 2989.6714 3241.6633 3497.8293 2971.4155 3053.2014 3246.9355 3251.9558
 2902.4006 2842.304  3263.3137 2848.3564 2790.6653 2662.0796 3062.3757
 2665.889  2888.3076 3738.3203 3110.0027 2768.17   2718.6838 2832.234
 2734.8315 3009.773  2974.0178 2968.2961 2804.6094 2663.2205 3246.906
 3653.1592 3234.6113 3005.192  3440.9949 2808.75   3230.7036 3143.5522
 3470.3433 2732.7112 2768.786  2996.3533 2954.7886 3012.32   2843.307
 2911.5212 3234.8118 2869.4387 3194.4236 2675.3447 2721.7131 2952.9963
 3310.5894 2789.9634 3103.166  3633.4724 3665.8064 3208.5598 2818.673
 2694.6692 3181.0747 3641.3718 3121.758  2799.9683 2760.363  3479.9937
 2845.797  2666.7234 2721.0125 3358.3713 2918.5022 3053.3528 2914.9387
 2948.2405 2927.2312 2771.9797 2878.04   3435.5994 2907.978  2825.582
 2911.363  2692.8196 2724.8345 4080.1333 3866.0146 4139.8467 2761.746
 2692.5425 2932.7844 3151.7837 2846.9177 3599.6042 3190.1362 2947.217
 2718.047  3293.8699 3152.5308 3215.8945 3484.446  3682.3813 3540.6775
 2660.7935 2721.8657 2733.6604 2689.6973 2674.636  2970.6882 3421.5652
 2687.776  2682.5144 2688.2798 2738.5063 2988.137  2976.3027 2898.2407
 3218.476  2749.8025 2727.5146 2654.6553 2670.0972 3077.786  2727.644
 3147.0464 2667.017  2762.2222 3238.483  3336.405  2764.2983 2744.3096
 2768.7603 2712.211  2711.0654 3019.3413 2707.9072 2871.4492 2940.3425
 3353.6245 2679.8796 2659.917  2741.3542 2690.0813 2886.985  2696.2656
 2974.0269 2961.9536 2926.1763 2662.5564 3045.8342 2668.79   3177.866
 2750.0088 2825.0369 2782.9631 3220.28   2733.2305 3064.9143 2664.8894
 3159.4377 2910.5483 2789.1038 3150.3042 3221.7515 3119.8538 2910.8206
 3344.8704 2679.364  3044.9106 3226.8035 3048.0103 3489.2744 3418.4124
 3434.6506 2760.9324 2685.1606 2816.0493 2881.8684 2914.1165 2883.6387
 2765.884  4127.344  4153.107  3041.3345 2804.4214 2744.9753 2713.6958
 3013.008  3000.6897 2983.313  2713.1897 3004.2505 3016.7156 3021.61
 2666.5989 3049.2183 3179.5742 2683.4033 3354.4353 2662.688  2706.945
 2874.8945 3135.91   2664.3674 3312.6091 2808.7393 2982.767  2989.4045
 3375.3596 3744.5417 2739.0154 2655.1294 3042.6584 2730.6716 2693.3228
 2665.8457 2766.929  2702.8066 3122.1006 2727.37   2761.2402 2847.9895
 3513.94   2720.7883 3487.2412 2852.9663 2814.4019 3475.8264 3087.0186
 3878.8533 3759.645  2723.0393 2918.926  2921.0935 2800.1768 2713.3513
 2958.4146 2969.7036 4221.2534 3180.4814 2764.6636 2808.5955 3274.713
 2697.39   2792.0522 2838.614  3276.8254 3075.7107 2961.781  3303.7747
 2769.0557 2695.6082 3392.0444 2807.2888 2872.8906 2673.0908 2699.0156
 3368.6426 2896.596  2681.775  2845.9941 2672.6667 3130.7458 2695.064
 2732.74   2711.8464 2977.0706 2691.209  2833.0847 3030.295  3084.674
 2786.7693 2985.6934 2858.0825 3854.6416 2900.3293 2835.7212 3021.256
 2703.5752 3084.8599 2928.853  2668.9963 2665.93   2848.0447 2848.349
 2708.2207 3370.1997 2970.035  2847.4644 2822.1292 2975.6694 2731.464
 2661.507  2692.423  2660.0342 2830.3113 2927.8447 2945.65   2657.5166
 2697.0725 2964.0464 2837.0308 3082.612  2860.4644 2750.8147 3135.0886
 3374.9019 2867.3208 3158.1167 2669.7231 2674.5237 2813.1821 3452.4502
 3130.3047 2769.3271 2846.7786 2811.07   2752.5835 2888.3738 2653.467
 3436.0454 2735.3276 2897.569  3219.5232 3512.6929 3532.0835 2735.3398
 2685.935  2856.002  2662.6401 2677.9917 3414.391  3043.2483 3032.0898
 2659.833  3107.697  3362.9438 2887.441  2788.2522 3482.6287 3374.905
 2700.3267 3171.2905 3021.2112 3282.7166 2885.02   3536.1301 3106.733
 2810.8728 2827.6619 3418.3005 3221.2795 2846.596  2974.0151 3240.9272
 2862.301  3123.383  2986.7498 2662.1516 2701.051  3683.4236 3092.6064
 2656.6611 2856.8433 2672.933  3303.3416 2687.426  3154.0679 2723.3118
 3732.387  2758.9104 2675.5754 2828.7856 3419.6272 2951.3848 2877.0886
 3079.5947 2685.5872 2666.346  2710.1914 2865.8047 2698.325  2661.5632
 2778.9707 3180.1091 3837.4153 2689.139  2695.1118 2701.489  2856.249
 3371.8567 2662.48   2677.984  2739.6943 3184.6836 2993.3672 2719.9197
 2729.829  2692.2378 2687.8748 2760.5127 2702.2275 2695.8765 3430.986
 3009.2998 2966.5925 3595.3806 3573.9165 2658.888  2732.0933 2770.4644
 2727.682  2662.1936 2654.797  2682.4758 2787.1177 2660.3184 2670.1948
 2813.1902 2739.1753 2869.5994 2656.925  2756.5725 2679.0093 2725.828
 2825.3977 3020.9255 3278.643  2661.068  2661.6938 2881.7837 2698.4028
 2733.782  2662.8784 2719.061  3183.363  3158.5562]

glicko_rd: [62.212624 63.886936 62.89943  88.22782  61.883877 96.36143  69.92723
 64.38748  67.018555 86.38825  95.05103  91.420006 66.28071  61.32222
 82.67274  75.442116 62.563686 96.55396  64.968704 81.64782  78.96452
 65.87309  59.60515  81.96681  63.06947  98.95932  77.13676  70.93632
 68.83645  73.08595  61.573204 71.45272  63.378063 63.91905  63.68328
 96.43591  65.25708  63.720306 64.15467  88.413666 64.44595  62.40243
 61.61253  61.70264  94.65278  61.797207 92.87874  62.732433 62.32658
 70.889435 63.176556 85.427216 63.494495 62.121094 62.80211  63.96965
 63.294544 69.14508  64.73596  63.536915 62.857185 64.35882  69.692184
 63.884003 81.447014 63.83859  63.47012  61.91774  87.85052  62.4398
 84.99181  62.547203 71.13112  66.19393  63.115234 62.20596  61.07506
 62.28668  63.321827 81.85098  75.89226  63.14079  94.844215 72.39608
 68.026184 63.939564 73.01693  65.92834  61.713512 63.479458 84.523254
 64.15975  98.25026  62.417377 63.905846 62.46835  63.9204   87.67174
 63.216873 63.8035   62.91421  78.35807  61.671932 62.107086 63.370132
 69.91743  63.121456 97.40422  65.39314  77.99344  65.84127  79.22449
 62.209545 76.20652  69.47906  63.550423 63.559235 61.241478 64.204735
 62.509632 61.609066 61.880756 74.376564 62.475147 63.114166 62.837032
 63.68676  63.906364 65.323784 62.761597 72.07436  62.79454  62.707436
 62.800446 61.684315 61.858547 65.19854  78.40008  68.198105 66.75688
 71.08652  71.72157  64.7241   62.323265 65.78113  84.79549  61.91303
 62.09346  64.59591  77.77586  65.19265  66.4054   67.74388  65.87382
 82.10233  62.74167  88.32072  67.66826  63.182774 67.41619  64.555214
 75.120804 77.48336  99.45391  64.27411  92.6863   64.80611  64.63292
 82.68784  61.89102  62.39671  62.72858  73.224365 63.80552  63.062614
 63.044376 72.74871  72.41344  64.151    86.042274 69.91701  62.475166
 71.951355 61.22728  66.30027  63.264904 86.33084  70.10969  62.73648
 66.067986 81.83725  91.20099  61.971657 62.392277 78.34219  62.44808
 81.20907  68.67525  66.14618  62.086937 67.96865  61.20104  66.791214
 91.02068  75.03392  62.40762  63.65257  62.632057 63.52403  61.70948
 76.64399  63.714024 73.96909  71.684364 63.62069  64.28154  72.56521
 65.05851  66.37218  90.03299  71.805244 63.397015 64.15365  86.36398
 66.70846  64.95585  62.299965 63.762333 68.296455 87.39036  63.191025
 63.046658 79.871605 72.20358  63.687023 69.60442  61.857754 67.765465
 62.687077 64.72398  85.78161  68.380936 71.45825  63.09275  63.368057
 66.74653  82.038506 64.34173  68.764465 63.785606 62.925335 62.321636
 66.853    63.08346  61.76456  67.442894 61.40674  67.281815 64.91213
 65.805046 63.62893  64.7709   62.796547 70.97631  66.547676 62.933464
 62.44211  75.981766 61.51121  64.78237  75.03977  62.68474  93.00206
 68.06946  66.69166  92.27672  62.65095  71.68902  66.45892  66.419044
 66.51279  86.2857   62.323788 80.27776  63.24167  62.860046 62.44436
 63.637268 69.549904 88.53588  77.090866 61.092884 71.55459  70.4056
 62.92263  61.28453  99.66458  65.443535 72.16279  95.38252  63.021507
 61.676968 72.11401  64.793106 84.133896 62.399956 98.3666   61.835567
 65.03296  63.86365  68.16592  63.243725 63.256573 88.54986  61.736996
 63.007576 61.49408  64.49329  66.34319  62.6166   62.516445 64.868095
 61.079205 63.208057 62.544064 72.6543   62.027504 63.952312 62.864643
 62.51575  61.771908 66.42986  63.856785 62.871666 63.870743 63.79796
 63.012535 84.933235 64.320015 65.79082  67.0656   62.96791  65.73708
 61.25571  62.445045 82.835144 68.00076  63.477825 64.06956  61.602676
 60.7413   96.59252  61.11283  63.20175  82.03029  62.477993 64.92873
 64.71529  73.67769  69.877365 61.329437 70.73224  65.34253  67.1641
 64.81807  62.165916 65.53445  68.91256  63.003036 66.26329  61.505684
 63.826744 78.20171  62.84046  87.913574 68.267006 66.78524  69.23256
 63.829456 63.791985 79.57936  62.88488  66.32126  65.07359  65.85136
 60.962036 67.6959   64.84423  62.64458  62.637188 70.85327  64.68398
 63.811234 75.25829  62.625675 69.45939  63.621456 66.49348  65.04706
 64.69472  62.9252   85.606636 64.4417   62.71652  89.10753  65.04083
 62.293083 63.70939  85.476456 61.546383 73.804985 67.70474  64.51185
 62.276142 73.4193   68.22709  65.51287  62.15051  65.01556  61.24906
 64.245544 70.88868  79.83799  62.24237  66.1305   66.006035 63.018852
 63.15402  76.111    61.763    63.4823   69.1107   66.31109  64.85158
 74.382    66.005424 79.082016 61.062923 68.02698  61.85858  62.88761
 99.05297  61.675846 62.46253  63.852448 64.28333  62.470535 62.52545
 72.0763   66.373055 62.135216 62.49782  80.31541  62.29695  96.63141
 65.40485  63.82384  67.68827  70.94594  62.526634 62.068874 62.02618
 62.074642 76.850395 64.98885  60.356724 77.45635  74.55523  61.32786
 90.95561  61.779224 64.938805 72.79387  73.634865 62.44826  89.125496
 67.11276  74.87644  64.46341  60.944164 84.248695 62.726364 80.31179
 62.41154  65.77791  66.612175 95.73479  80.98635 ]

Based from the results, there are no default values nor inconsistent formatting present in any of the variables

However, it can be seen that the only value for `garbage_cleared` is **0**, which makes it essentially useless and unnecessary to keep moving forward.

In [53]:
df = df.drop(columns=['garbage_cleared'])

### Checking for Duplicate Data

This is done to check for any rows that have the exact same values

In [54]:
df.duplicated().any()

np.True_

Results show that there are rows with the exact same values, which should not be possible especially if rows in one game contain the same subframes as it is physically impossible to have two or more pieces placed within the same subframe

In [55]:
df = df.drop_duplicates(subset=["game_id", "subframe"])
df.shape

(7716512, 13)

This shows that 12 rows have been removed from the intial amount of rows after duplicate rows with the same `game_id` and `subframe`

### Checking for Inconsistent Games

This is to check for inconsistencies within the games. Variables like a player's starting `rating`, `glicko`, `glicko_rd`, and whether they `won` the match should be identical for every single piece placed within the same game

In [56]:
if {"game_id", "won", "rating", "glicko", "glicko_rd"}.issubset(df.columns):
    gchecks = df.groupby("game_id")[["won", "rating", "glicko", "glicko_rd"]].nunique()
    inconsistent_games = gchecks[(gchecks > 1).any(axis=1)].index.tolist()
    print(f"Inconsistent games found: {len(inconsistent_games)}")
    df = df[~df["game_id"].isin(inconsistent_games)]

Inconsistent games found: 0

Based on the results, no inconsistencies where found within the games

### Checking for Outliers

This is done to check for outliers within the numerical variables the will be used. This was done through statistical and frequency-based outlier detection, specifically doing a percentile and frequency check. This process was chosen over using visualizations since we are dealing with 7.7 million rows for now

In [57]:
num_cols = [
    "cleared",
    "attack",
    "btb",
    "combo",
    "immediate_garbage",
    "incoming_garbage",
]
for col in num_cols:
    if col in df.columns:
        high = df[col].quantile(0.999)
        low = df[col].quantile(0.001)
        print(f"{col}: min={df[col].min()}, max={
              df[col].max()}, 0.1%={low}, 99.9%={high}")

for col in num_cols:
    if col in df.columns:
        top_values = df[col].value_counts().nlargest(5).to_dict()

        max_val = df[col].max()

        print(f"--- {col} ---")
        print(f"Max Value: {max_val}")
        print(f"Top 5 most common values: {top_values}\n")

cleared: min=0, max=4, 0.1%=0.0, 99.9%=4.0
attack: min=0, max=22, 0.1%=0.0, 99.9%=7.0
btb: min=0, max=54, 0.1%=0.0, 99.9%=19.0
combo: min=0, max=21, 0.1%=0.0, 99.9%=7.0
immediate_garbage: min=0, max=78, 0.1%=0.0, 99.9%=15.0
incoming_garbage: min=0, max=78, 0.1%=0.0, 99.9%=17.0
--- cleared ---
Max Value: 4
Top 5 most common values: {0: 5587283, 1: 958295, 2: 690330, 4: 381767, 3: 98837}

--- attack ---
Max Value: 22
Top 5 most common values: {0: 6033910, 1: 590235, 4: 439143, 2: 207244, 5: 197437}

--- btb ---
Max Value: 54
Top 5 most common values: {0: 3580652, 1: 1467989, 2: 890306, 3: 553606, 4: 388236}

--- combo ---
Max Value: 21
Top 5 most common values: {0: 5596511, 1: 1315812, 2: 445764, 3: 197292, 4: 88032}

--- immediate_garbage ---
Max Value: 78
Top 5 most common values: {0: 6690409, 1: 243668, 5: 150719, 4: 149941, 2: 148039}

--- incoming_garbage ---
Max Value: 78
Top 5 most common values: {0: 5866748, 1: 380035, 5: 290027, 4: 277661, 2: 265844}

The results show that the data for `cleared` is perfect and expected since a player can clear 0, 1, 2, 3, or 4 lines (a Tetris) with a single piece.

Furthemore, extreme but valid gameplay spikes can be observed for `combo`. A 21-combo usually indicates a perfectly executed center 4-wide or side 4-wide setup, which is possible.

Moreover, spikes can be observed for `attack`, `btb`, `immediate_garbage`, and `incoming_garbage` as they similarly have a relatively low value for the 99.9% quantile but have a huge maximum value. Again, these are valid extremes and are possible in a game. In Tetrio, attack scales massively with B2B and combo multipliers. A B2B Tetris at the end of a 10+ combo can absolutely spike damage into the 20s in a single subframe, a 54 B2B chain means a player continuously maintained T-spins and Tetrises for almost the entire game, and 78 lines of incoming garbage means a player had a massive red bar of garbage waiting to enter their board and end the game.

**We decided to keep these extreme values as these are essentially highlights or game-winning moves of players. Considering that this data is from the Top 500 players, the extreme values are markers of specific and elite playstyles.**

### Feature Engineering

This is done to transform the data into more meaningful features by aggregating the data by their `game_id` to work on a game/match level as it adheres to our prediction goal that requires analysis on an entire match instead of individual piece placements

In [58]:
agg_dict = {
    "subframe": ["max", "count"],
    "cleared": "sum",
    "attack": "sum",
    "t_spin": lambda x: x.isin(["M", "F"]).sum(),
    "btb": ["mean", "max"],
    "combo": ["mean", "max"],
    "immediate_garbage": ["mean", "max"],
    "incoming_garbage": ["mean", "max"],
    "won": "first",
    "rating": "first",
    "glicko": "first",
    "glicko_rd": "first",
}

game_level = df.groupby("game_id").agg(agg_dict)

game_level.columns = ["_".join([c for c in col if c]) for col in game_level.columns]
game_level = game_level.reset_index()

rename_map = {
    "t_spin_<lambda>": "t_spin_count",
    "won_first": "won",
    "rating_first": "rating",
    "glicko_first": "glicko",
    "glicko_rd_first": "glicko_rd",
}
game_level = game_level.rename(columns=rename_map)

game_level["duration_sec"] = game_level["subframe_max"] / 600
game_level["pps"] = game_level["subframe_count"] / game_level["duration_sec"]
game_level["attack_per_piece"] = game_level["attack_sum"] / game_level["subframe_count"]
game_level["apm"] = (game_level["attack_sum"] / game_level["duration_sec"]) * 60
game_level["tspin_rate"] = game_level["t_spin_count"] / game_level["subframe_count"]

print("Num rows in game_level:", len(game_level))

Num rows in game_level: 76692

From 7,716,512 rows, we are now dealing with 76,692 rows, each of which representing one game/match. Along with this, most of columns have been transformed and is now utilizing mean and maximum values (`btb_mean`, `btb_max`, `combo_mean`, `combo_max`, `immediate_garbage_mean`, `immediate_garbage_max`, `incoming_garbage_mean`, `incoming_garbage_max`) and rates (`pps` or piece per second, `attack_per_piece`, `apm` or attack per minute, and	`tspin_rate`), while columns like `won`, `rating`, `glicko`, and `glicko_rd` have been retained. Additionally, a `duration_sec` was also made and represents the duration of the game, in seconds

With that, we decided to drop the games/matches that lasted for less than 10 seconds to rule out instant disconnections and forfeits

In [59]:
game_level = game_level[game_level["duration_sec"] >= 10.0].copy()
game_level.shape

(70246, 23)

Lastly, as the current data still contains intermediate columns from the process of aggregation, it has no more use and needs to be dropped. The game_id identifier must also be dropped as it should not be used during model training

In [60]:
cols_to_drop = [
    "game_id",
    "subframe_max",
    "subframe_count",
    "cleared_sum",   
    "attack_sum",
    "t_spin_count"
]

final_df = game_level.drop(columns=cols_to_drop)
final_df.head()

,btb_mean,btb_max,combo_mean,combo_max,immediate_garbage_mean,immediate_garbage_max,incoming_garbage_mean,incoming_garbage_max,won,rating,glicko,glicko_rd,duration_sec,pps,attack_per_piece,apm,tspin_rate
0,1.933673,8,0.520408,7,0.244898,8,0.576531,15,1,24748.521484,2701.887695,62.212624,70.600000,2.776204,0.821429,136.827195,0.076531
1,0.413953,4,0.590698,6,0.683721,13,1.432558,13,0,24820.710938,2791.866943,63.886936,71.310000,3.015005,0.586047,106.015987,0.055814
2,0.611842,3,0.605263,8,0.250000,6,0.605263,6,1,24820.710938,2791.866943,63.886936,49.275000,3.084729,0.671053,124.200913,0.065789
3,0.786765,4,0.588235,6,0.551471,9,1.227941,10,0,24748.521484,2701.887695,62.212624,49.283333,2.759554,0.625000,103.483260,0.036765
4,1.277487,7,0.539267,5,0.366492,11,0.691099,11,1,24748.521484,2701.887695,62.212624,69.525000,2.747213,0.670157,110.463862,0.057592

In [61]:
# Optionally export the processed data
# final_df.to_csv("../data/data_processed.csv", index=False)